#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=9dc9ff403850282bbbbeb93d16b34837932d01a1
fi

# conflict인 경우 clang-format 적용하지 않음
if grep "Conflicts" .git/MERGE_MSG > /dev/null 2>&1
then
    echo conflict occurred... skip hook
    exit 0
fi

# 색 정의
RED="\e[0;31m"
END="\e[0m"

# Do format checking (clang-format)
C_CXX_format="\.([ch]|[chi](pp|xx)|(cc|hh|ii)|[CHI])$"
for file in `git diff-index --cached --name-only $against | grep -Ee "$C_CXX_format"`
do
  AUTOFORMATTER=`which clang-format`
  if [ "$AUTOFORMATTER" = "" ]
  then
    echo -n "${RED}Cannot find clang-format\nPlease run package install script : trunk/pkg/install_linux_pkg.sh ${END}\n"
    exit 1
  else
    if $AUTOFORMATTER "$file" -output-replacements-xml | grep -c "<replacement " > /dev/null
    then
      echo -n "\"$file\" is not formatted.\n"
      $AUTOFORMATTER -i "$file"
      git add "$file"
      echo -n "Auto formatting applied: $AUTOFORMATTER\n"
    fi
  fi
done

# Do default checking (trailing whitespace, etc.)
git diff-index --check --cached $against . ':(exclude)*.patch'
